version: 2
builds:
  - binary: cliindexer
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

publish:
  brews:
    - name: cli-indexer
      homepage: https://github.com/fishmanDK/cli-indexer
      tap:
        owner: fishmanDK
        name: homebrew-cli-indexer
      commit_author:
        name: fishmanDK
        email: denis.23weer@gmail.com

checksums:
  - name_template: 'checksums.txt'
